build(deps): update angular-cli to f5b1a9e
Also adding `ng2-pdfjs-viewer-ngcc` to the list of projects failing in
ES5 mode. The [currently recommended][1] way to use `ng2-pdfjs-viewer`
is to copy `ng2-pdfjs-viewer/pdfjs/` sub-directory to assets
([which we do][2]), but this breaks with the latest CLI in ES5 mode,
because that sub-directory contains non-ES5 compatible code (`let`
declarations, `for...of` loops, etc.).

[Example CI failure][3]:
```
Error: Optimization error [assets/pdfjs/web/debugger.js]: Error: Transform failed with 16 errors:
assets/pdfjs/web/debugger.js:24:4: error: Transforming let to the configured target environment ("es5") is not supported yet
assets/pdfjs/web/debugger.js:25:9: error: Transforming let to the configured target environment ("es5") is not supported yet
assets/pdfjs/web/debugger.js:25:17: error: Transforming for-of loops to the configured target environment ("es5") is not supported yet
assets/pdfjs/web/debugger.js:30:4: error: Transforming let to the configured target environment ("es5") is not supported yet
assets/pdfjs/web/debugger.js:31:9: error: Transforming let to the configured target environment ("es5") is not supported yet
...
```

[1]: https://github.com/intbot/ng2-pdfjs-viewer/tree/97cf53dee15a17284c8c7b3693e50ef4f3c2e700#step-2-copy-task-for-pdfjs
[2]: https://github.com/angular/ngcc-validation/blob/8591342a2614657b55d1672e790c35429df3fb7e/angular.json#L14769-L14773
[3]: https://circleci.com/gh/angular/ngcc-validation/46331