ci(Renovate): automatically update `browserslist` DB
When `browserslist` is updated (as part of the Angular CLI updates) it
often needs to also have the browsers DB updated. Failing to do so can
result in built-time error like the foloowing ([example failure][1]):

```
BrowserslistError: Unknown version 101 of android
```

This commit avoids such errors by always updating the `browserslist` DB
when updating the Angular CLI version.

[1]: https://circleci.com/gh/angular/ngcc-validation/105342